---

version: "v-{build}"

image: Visual Studio 2017

clone_folder: C:\projects\babashka

environment:
  GOPATH: C:\gopath
  CGO_ENABLED: 1
  GOVERSION: 119

install:
  - set GOROOT=C:\go%GOVERSION%
  - set PATH=%GOPATH%\bin;%GOROOT%\bin;%PATH%
  - go version
  - go env

cache:
  - 'C:/gopath/pkg/mod -> go.sum, appveyor.yml'

clone_script:
- ps: >-
    if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      git clone -q --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git checkout -qf $env:APPVEYOR_REPO_COMMIT
    } else {
      git clone -q https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
      git checkout -qf FETCH_HEAD
    }
- cmd: git submodule update --init --recursive

build_script:

- cmd: >-

    set PATH=C:\msys64\mingw64\bin;%PATH%

    go build -o pod-babashka-go-sqlite3.exe main.go

    set /P VERSION=< resources\POD_BABASHKA_GO_SQLITE3_VERSION

    jar -cMf pod-babashka-go-sqlite3-%VERSION%-windows-amd64.zip pod-babashka-go-sqlite3.exe

artifacts:
- path: pod-babashka-go-sqlite3-*-windows-amd64.zip
  name: pod-babashka-go-sqlite3
