---

version: "v-{build}"

image: Visual Studio 2017

clone_folder: C:\projects\babashka

environment:
  GOPATH: c:\gopath
  CGO_ENABLED: 1

cache:
  - '/go/pkg/mod -> go.sum, appveyor.yml'

clone_script:
- ps: >-
    if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      git clone -q --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git checkout -qf $env:APPVEYOR_REPO_COMMIT
    } else {
      git clone -q https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
      git checkout -qf FETCH_HEAD
    }
- cmd: git submodule update --init --recursive

build_script:

- cmd: >-
    go build -o pod-babashka-sqlite3.exe main.go

    set /P VERSION=< resources\POD_BABASHKA_SQLITE3_VERSION

    jar -cMf pod-babashka-sqlite3-%VERSION%-windows-amd64.zip pod-babashka-buddy.exe

artifacts:
- path: pod-babashka-sqlite3-*-windows-amd64.zip
  name: pod-babashka-sqlite3
