version: 2.1

jobs:
  linux:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - pod-babashka-go-sqlite3-{{ checksum "go.sum" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Build binary
          command: go build -o pod-babashka-go-sqlite3 main.go
      - run:
          name: Install bb for test
          command: |
            mkdir bb
            bash <(curl -sL https://raw.githubusercontent.com/borkdude/babashka/master/install) \
              --dir bb --download-dir bb
      - run:
          name: Run test
          command: PATH=$PATH:bb script/test
      - save_cache:
          key: pod-babashka-go-sqlite3-{{ checksum "go.sum" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Release
          command: |
            VERSION=$(cat resources/POD_BABASHKA_GO_SQLITE3_VERSION)
            mkdir release

            zip "release/pod-babashka-go-sqlite3-$VERSION-linux-amd64.zip" pod-babashka-go-sqlite3
      - store_artifacts:
          path: release
          destination: release
  mac:
    macos:
      xcode: 12.0.0
    steps:
      - checkout
      - run:
          name: Install Go
          command: curl -L https://git.io/vQhTU | bash && source /Users/distiller/.bashrc
      - restore_cache:
          keys:
            - pod-babashka-go-sqlite3-{{ checksum "go.sum" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Build binary
          command: |
            source /Users/$(whoami)/.bashrc

            go build -o pod-babashka-go-sqlite3 main.go
      - run:
          name: Install bb for test
          command: |
            mkdir bb
            bash <(curl -sL https://raw.githubusercontent.com/borkdude/babashka/master/install) \
              --dir bb --download-dir bb
      - run:
          name: Run test
          command: PATH=$PATH:bb script/test
      - save_cache:
          key: pod-babashka-go-sqlite3-{{ checksum "go.sum" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Release
          command: |
            VERSION=$(cat resources/POD_BABASHKA_GO_SQLITE3_VERSION)
            mkdir release

            zip "release/pod-babashka-go-sqlite3-$VERSION-macos-amd64.zip" pod-babashka-go-sqlite3
      - store_artifacts:
          path: release
          destination: release

workflows:
  version: 2
  ci:
    jobs:
      - linux
      - mac
