version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - pod-babashka-sqlite3-{{ checksum "go.sum" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Is sqlite installed?
          command: sqlite --version
      - run:
          name: Build linux binary
          command: go build -o linux-amd64/pod-babashka-sqlite3 main.go
      - run:
          name: Build mac binary
          environment:
            GOOS: darwin
            GOARCH: amd64
          command: go build -o macos-amd64/pod-babashka-sqlite3 main.go
      - run:
          name: Build windows binary
          environment:
            GOOS: windows
            GOARCH: amd64
          command: go build -o windows-amd64/pod-babashka-sqlite3.exe main.go
      # - run:
      #     name: Install bb for test
      #     command: |
      #         mkdir bb
      #         bash <(curl -sL https://raw.githubusercontent.com/borkdude/babashka/master/install) \
      #           --dir bb --download-dir bb
      # - run:
      #     name: Run test
      #     command: cp linux-amd64/pod-babashka-fswatcher . && PATH=$PATH:bb script/test
      - run:
          name: Test fiddle
          command: |
              go run fiddle.go
      - save_cache:
          key: pod-babashka-sqlite3-{{ checksum "go.sum" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - "/go/pkg/mod"
      # - run:
      #     name: Release
      #     command: |
      #       VERSION=$(cat resources/POD_BABASHKA_FSWATCHER_VERSION)
      #       mkdir release

      #       zip -j "release/pod-babashka-fswatcher-$VERSION-linux-amd64.zip" linux-amd64/pod-babashka-fswatcher
      #       zip -j "release/pod-babashka-fswatcher-$VERSION-macos-amd64.zip" macos-amd64/pod-babashka-fswatcher
      #       zip -j "release/pod-babashka-fswatcher-$VERSION-windows-amd64.zip" windows-amd64/pod-babashka-fswatcher.exe
      # - store_artifacts:
      #     path: release
      #     destination: release

workflows:
  version: 2
  ci:
    jobs:
      - build
